#Numpy   Numerical python(library)

In [7]:
!pip install numpy      #python installing package

In [8]:
import numpy as np    #as means - alias

#Array
1. 1 column multi rows  1 axis (x) called as 1 D(dimensional) array
   and 1 row multi column called as indexing as well as 1 D array.
   shown as [  ]

2. multi (max 2) column and row  2 axis (x and y) called as 2 D array. shown as [[  ]]

3. 3 axis (x,y,z) called as 3D array. shown as [[[  ]]]




In [9]:
#creating array

In [10]:
arr = np.array([1,2,3,4,5,6])

In [11]:
arr

array([1, 2, 3, 4, 5, 6])

In [12]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [13]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr2 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [17]:
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
arr3 = np.array([[[1,2,3,4]]])

In [33]:
arr3

array([[[1, 2, 3, 4]]])

#Array Properties


print(arr.ndim) #Dimensions
print(arr.shape) #Shape
print(arr.size) #Total element
print(arr.dtype) #Data type

In [34]:
arr1.ndim

2

In [35]:
arr2.ndim

3

In [36]:
arr3.ndim

3

# Numpy Properties

In [37]:
arr2.shape

(2, 2, 2)

In [39]:
arr3.shape

(1, 1, 4)

In [42]:
np.shape(arr3)

(1, 1, 4)

In [43]:
np.size(arr3)

4

In [45]:
arr3.dtype

dtype('int64')

#Array Slicing - indexing

In [46]:
arr

array([1, 2, 3, 4, 5, 6])

In [47]:
arr[2]

3

In [49]:
arr[2:5]

array([3, 4, 5])

In [51]:
arr[:4]

array([1, 2, 3, 4])

In [52]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr1[1,0]   #1st row,  0th column

4

In [54]:
arr1[1,1]

5

In [56]:
arr1[1,2]

6

#Arithmatic Operations

In [58]:
arr1 = np.array ([1,2,3,4])
arr2 = np.array ([4,5,6,7])

In [59]:
arr1 + arr2

array([ 5,  7,  9, 11])

In [60]:
arr1*arr2

array([ 4, 10, 18, 28])

In [61]:
arr1 + 10     #broadcasting

array([11, 12, 13, 14])

#Advanced Operations

In [62]:
arr

array([1, 2, 3, 4, 5, 6])

In [63]:
arr.sum()

21

In [64]:
arr.mean()

3.5

In [67]:
arr.max()

6

In [68]:
arr.std()

1.707825127659933

In [69]:
arr.min()

1

In [72]:
np.median(arr1)

2.5

In [73]:
arr

array([1, 2, 3, 4, 5, 6])

In [76]:
print(arr.T)

[1 2 3 4 5 6]


#Special Functions

In [77]:
zeros = np.zeros((2,3))

In [78]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [79]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [80]:
np.ones(4)

array([1., 1., 1., 1.])

In [81]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [85]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [86]:
np.empty(5)

array([4.95627424e-310, 0.00000000e+000, 2.41907520e-312, 2.56761491e-312,
       2.37151510e-322])

In [87]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [89]:
np.linspace(0,1,5)   #particular spaces

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [90]:
arr

array([1, 2, 3, 4, 5, 6])

In [91]:
arr.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])