#NumPy - Numerical Python

In [ ]:
!pip install numpy    #python installing package

In [ ]:
import numpy as np     #as - alias

In [ ]:
#creating arrays

In [ ]:
arr = np.array([1,2,3,4,5,6])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = np.array([[1,2,3], [4,5,6]])

In [ ]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2 = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])

In [ ]:
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
arr3 = np.array([[[1,2,3,4]]])

#array properties
print(arr.ndim)   # Dimensions

print(arr.shape)  # Shape

print(arr.size)   # Total elements

print(arr.dtype)  # Data type


In [ ]:
arr.ndim

1

In [ ]:
arr1.ndim

2

In [ ]:
arr2.ndim

3

In [ ]:
arr3.ndim

3

In [ ]:
arr2.shape

(2, 2, 2)

In [ ]:
arr3.shape

(1, 1, 4)

In [23]:
np.shape(arr3)

(1, 1, 4)

In [24]:
np.size(arr3)

4

In [26]:
arr3.dtype

dtype('int64')

#array slicing - indexing

In [27]:
arr

array([1, 2, 3, 4, 5, 6])

In [28]:
arr[2]

3

In [29]:
arr[2:5]

array([3, 4, 5])

In [30]:
arr[:4]

array([1, 2, 3, 4])

In [31]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr1[1,0]   #1st row, oth column

4

In [34]:
arr1[1,1]

5

In [35]:
arr1[1,2]

6

#arithmatic operations

In [36]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,5,6,7])

In [37]:
arr1 + arr2

array([ 5,  7,  9, 11])

In [38]:
arr1 * arr2

array([ 4, 10, 18, 28])

In [39]:
arr1 + 10   #broadcasting

array([11, 12, 13, 14])

#advance operations

In [40]:
arr

array([1, 2, 3, 4, 5, 6])

In [41]:
arr.sum()

21

In [42]:
arr.mean()

3.5

In [43]:
arr.max()

6

In [44]:
arr.min()

1

In [45]:
arr.std()

1.707825127659933

In [46]:
np.median(arr)

3.5

In [47]:
arr

array([1, 2, 3, 4, 5, 6])

In [49]:
print(arr.T)

[1 2 3 4 5 6]


#special functions

In [50]:
zeros = np.zeros((2,3))

In [51]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [53]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [54]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.full(5,7)

array([7, 7, 7, 7, 7])

In [57]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [60]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [61]:
arr

array([1, 2, 3, 4, 5, 6])

In [62]:
arr.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])